{
  "formatVersion": "1.1",
  "component": {
    "group": "stream.spalla",
    "module": "spalla-android-sdk",
    "version": "1.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "spalla-android-sdk-1.4.0.aar",
          "url": "spalla-android-sdk-1.4.0.aar",
          "size": 153855,
          "sha512": "16ffa41578f9ec1101e2cd4b41cf68769bee4176b3e00f977f0b18707afe70429799d7c0755941db1fc317974ee2d1c9f22a3e96fa732857c2a87271adaade84",
          "sha256": "875ef1961c6d8a207f064b373c55252178423249e719b6bee363275afaa73e5c",
          "sha1": "c91563c2f384fa5f82a3a0c5eec279082b2a5c95",
          "md5": "3a4b4baa94b9f75cc5f3ca3eb8b401e9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.4"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2024.10.01"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-extended"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "com.theoplayer.theoplayer-sdk-android",
          "module": "core",
          "version": {
            "requires": "8.+"
          }
        },
        {
          "group": "com.theoplayer.theoplayer-sdk-android",
          "module": "integration-cast",
          "version": {
            "requires": "8.+"
          }
        },
        {
          "group": "com.theoplayer.android-ui",
          "module": "android-ui",
          "version": {
            "requires": "1.+"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-cast-framework",
          "version": {
            "requires": "21.3.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.picasso",
          "module": "picasso",
          "version": {
            "requires": "2.71828"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "spalla-android-sdk-1.4.0.aar",
          "url": "spalla-android-sdk-1.4.0.aar",
          "size": 153855,
          "sha512": "16ffa41578f9ec1101e2cd4b41cf68769bee4176b3e00f977f0b18707afe70429799d7c0755941db1fc317974ee2d1c9f22a3e96fa732857c2a87271adaade84",
          "sha256": "875ef1961c6d8a207f064b373c55252178423249e719b6bee363275afaa73e5c",
          "sha1": "c91563c2f384fa5f82a3a0c5eec279082b2a5c95",
          "md5": "3a4b4baa94b9f75cc5f3ca3eb8b401e9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spalla-android-sdk-1.4.0-sources.jar",
          "url": "spalla-android-sdk-1.4.0-sources.jar",
          "size": 50574,
          "sha512": "2afc2711fa414dc857c496ee2edb1d0145dbbf9e02ac84fcf0e120519c1448d8e5767c05e4c1d1ad3f02ed6b572a90fb378f988a367bdfededa0064b87330ae3",
          "sha256": "938c5395e6e2f26ee6da7be09898b443b15dd5c8db84758391573c516611b4d8",
          "sha1": "29b74761392405bec6e73a072f7dc216c24bf4c2",
          "md5": "ec7058e04085226422cb160ed74d4391"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spalla-android-sdk-1.4.0-javadoc.jar",
          "url": "spalla-android-sdk-1.4.0-javadoc.jar",
          "size": 461222,
          "sha512": "a97ce2c8860059f4e8fa3c1c7624875fd2bf98114b614824c4de8939df3aa23d1a42e64f6ecb8f9358539cc7fc4edaf921766d264b2137523ccbe6c537cc1389",
          "sha256": "ff1dfd0b5fabeafc000541c44c9ecce5332d22baef258947388f6826a7fe8c83",
          "sha1": "d27e097525bdafcce1bc068d2f57f75f20ea63bc",
          "md5": "b9bbb6c0e70bbcf03be7a68750bcf472"
        }
      ]
    }
  ]
}
