{
  "formatVersion": "1.1",
  "component": {
    "group": "stream.spalla",
    "module": "spalla-android-sdk",
    "version": "1.6.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "spalla-android-sdk-1.6.0.aar",
          "url": "spalla-android-sdk-1.6.0.aar",
          "size": 734229,
          "sha512": "7eb83f96e7932b0540780a2b28227a417663aa32e74602e2deaf7dad13d42116818bde9a774a347c1b98f5821705d2b3459bede0f656c6a77c3c3b3c6084cfab",
          "sha256": "082a80696aa912f172c5d243c024f06a5c3aacbe2a7fd3e3f124fbbc3ebf269c",
          "sha1": "0488459fb7006d5de50eff82d3736138ad41ac63",
          "md5": "0e587fb8f2d64de9a768e7da2a11dfe6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.4"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2024.10.01"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-extended"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "com.theoplayer.theoplayer-sdk-android",
          "module": "core",
          "version": {
            "requires": "8.10.0"
          }
        },
        {
          "group": "com.theoplayer.theoplayer-sdk-android",
          "module": "integration-cast",
          "version": {
            "requires": "8.10.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-cast-framework",
          "version": {
            "requires": "21.3.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.picasso",
          "module": "picasso",
          "version": {
            "requires": "2.71828"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "spalla-android-sdk-1.6.0.aar",
          "url": "spalla-android-sdk-1.6.0.aar",
          "size": 734229,
          "sha512": "7eb83f96e7932b0540780a2b28227a417663aa32e74602e2deaf7dad13d42116818bde9a774a347c1b98f5821705d2b3459bede0f656c6a77c3c3b3c6084cfab",
          "sha256": "082a80696aa912f172c5d243c024f06a5c3aacbe2a7fd3e3f124fbbc3ebf269c",
          "sha1": "0488459fb7006d5de50eff82d3736138ad41ac63",
          "md5": "0e587fb8f2d64de9a768e7da2a11dfe6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spalla-android-sdk-1.6.0-sources.jar",
          "url": "spalla-android-sdk-1.6.0-sources.jar",
          "size": 95432,
          "sha512": "f8927a625d816691f3e963c593129e90e50cf142fb47706ce2c37ead15d01f733dd45292a19032794c72b69758bae2e83363d939ec29f18806c42f1d74263fe1",
          "sha256": "8b39588c788f82446415f6a60946f6dc6987ed64fd89daee36535ae5bfd71255",
          "sha1": "0b339f72e8f2553033b5f60870e68fea3714b9c0",
          "md5": "8415580b8bef7c9410e1d4d312bdaee7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spalla-android-sdk-1.6.0-javadoc.jar",
          "url": "spalla-android-sdk-1.6.0-javadoc.jar",
          "size": 496982,
          "sha512": "263c6d6af667586589511edbdeaa38fdd1924ba2f21c4538ae034cb31496cbb1d18947e3146c0b2e7ed733f49adb49880248c6b1e6924703edf297e17d90554d",
          "sha256": "dabf4cd895af5062c954b68d006625c1df8123f8c7dbed3f2f33da8246c9cea3",
          "sha1": "89ef562944dcd4c9cd7ce90ce372612df808334a",
          "md5": "4e3f99bfca8af3719bff629355745700"
        }
      ]
    }
  ]
}
