{
  "formatVersion": "1.1",
  "component": {
    "group": "stream.spalla",
    "module": "spalla-android-sdk",
    "version": "1.2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.21"
          }
        }
      ],
      "files": [
        {
          "name": "spalla-android-sdk-1.2.2.aar",
          "url": "spalla-android-sdk-1.2.2.aar",
          "size": 159785,
          "sha512": "f8ec87a55327a80751a1be0f24f0221f25ac6891e55c0094df66a46f67676b285d1d9c19ab77a6327bc898e06604ae2f9216eb425ceb8cc5765495e1b471596e",
          "sha256": "21433005072fc6a248775e72e1eedbc7b64d8fae701c750e2b7be813a12dfc6a",
          "sha1": "45e1f7a6029d321084107df9c6a92cf500606dd5",
          "md5": "3a91d241c69d339034bf6950defbd3c3"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.21"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.4"
          }
        },
        {
          "group": "com.theoplayer.theoplayer-sdk-android",
          "module": "basic-minapi21",
          "version": {
            "requires": "4.12.2"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-cast-framework",
          "version": {
            "requires": "21.3.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.picasso",
          "module": "picasso",
          "version": {
            "requires": "2.71828"
          }
        }
      ],
      "files": [
        {
          "name": "spalla-android-sdk-1.2.2.aar",
          "url": "spalla-android-sdk-1.2.2.aar",
          "size": 159785,
          "sha512": "f8ec87a55327a80751a1be0f24f0221f25ac6891e55c0094df66a46f67676b285d1d9c19ab77a6327bc898e06604ae2f9216eb425ceb8cc5765495e1b471596e",
          "sha256": "21433005072fc6a248775e72e1eedbc7b64d8fae701c750e2b7be813a12dfc6a",
          "sha1": "45e1f7a6029d321084107df9c6a92cf500606dd5",
          "md5": "3a91d241c69d339034bf6950defbd3c3"
        }
      ]
    }
  ]
}
