{
  "formatVersion": "1.1",
  "component": {
    "group": "stream.spalla",
    "module": "spalla-android-sdk",
    "version": "1.9.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "spalla-android-sdk-1.9.4.aar",
          "url": "spalla-android-sdk-1.9.4.aar",
          "size": 747827,
          "sha512": "917643b1d63784895f0b465aa4863f78aad21061e8ea1310df46406423408713bedaba49501a6c56fd9d1c05e47d94e1de77890c8a8dcd9754683fe097740d48",
          "sha256": "6776a58a98b71711960f5e5be00d0c4512569f860e52440b767176f4bd45b71c",
          "sha1": "e7a15c8cd3880cf605db5bedd151d7d312bc71ec",
          "md5": "409111723107d9c94672b40cd74aebfc"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.4"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2024.10.01"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-extended"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "com.theoplayer.theoplayer-sdk-android",
          "module": "core",
          "version": {
            "requires": "8.10.0"
          }
        },
        {
          "group": "com.theoplayer.theoplayer-sdk-android",
          "module": "integration-cast",
          "version": {
            "requires": "8.10.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-cast-framework",
          "version": {
            "requires": "21.3.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.picasso",
          "module": "picasso",
          "version": {
            "requires": "2.71828"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "spalla-android-sdk-1.9.4.aar",
          "url": "spalla-android-sdk-1.9.4.aar",
          "size": 747827,
          "sha512": "917643b1d63784895f0b465aa4863f78aad21061e8ea1310df46406423408713bedaba49501a6c56fd9d1c05e47d94e1de77890c8a8dcd9754683fe097740d48",
          "sha256": "6776a58a98b71711960f5e5be00d0c4512569f860e52440b767176f4bd45b71c",
          "sha1": "e7a15c8cd3880cf605db5bedd151d7d312bc71ec",
          "md5": "409111723107d9c94672b40cd74aebfc"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spalla-android-sdk-1.9.4-sources.jar",
          "url": "spalla-android-sdk-1.9.4-sources.jar",
          "size": 97671,
          "sha512": "9223b926274f42550f8288222341f5e10965a8c8619a0c0987ee11aedc4fba6187c69f4e954290d305de0aae827767f15635f33c7b01ac2544eedcc013a357ae",
          "sha256": "de0dacef7a017002b32bfa75f8257e9061b04355799e29d1032e394a63cf00b6",
          "sha1": "708921ea9c2da8ab5b3aa70c28b32b93a48a10a0",
          "md5": "3e04ef5d630713bddc8f9e456fbd05d0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spalla-android-sdk-1.9.4-javadoc.jar",
          "url": "spalla-android-sdk-1.9.4-javadoc.jar",
          "size": 506566,
          "sha512": "88c0c0ee01e40340e6910ae8bb948ba0467743a43bae56f2486e858d918e4a00930151c3632c46beefd5b171f93a2d01f02b9d9a6abc35070ad9eedbfef3cc46",
          "sha256": "092f206b1fce131a32fdcf164b9be0e9f91b44aa707f1fd0c0305d4d7799c14e",
          "sha1": "b8a9ee25d631b754a17eea43ebf4a7dfb574d8c5",
          "md5": "2687e5f182ca81e1dac618556d7f11da"
        }
      ]
    }
  ]
}
