{
  "formatVersion": "1.1",
  "component": {
    "group": "stream.spalla",
    "module": "spalla-android-sdk",
    "version": "1.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.21"
          }
        }
      ],
      "files": [
        {
          "name": "spalla-android-sdk-1.2.0.aar",
          "url": "spalla-android-sdk-1.2.0.aar",
          "size": 159555,
          "sha512": "98c546a73e4611d46f8b0ccb6a6c8c4cf193afe5ca3d901e617d70bab964aab3842bf7aad7b804389b6b8cfcf64ad3c6e3de909781bddc06dd5076763bd5882c",
          "sha256": "556b883ade442e4f0b64f39d613f9489102fbad75a2b860ce907e6309c73b757",
          "sha1": "5d31c846c50fe41f36bd9ea8e002cfa42aeda047",
          "md5": "c595861678ee4e378b4792484a761178"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.21"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.4"
          }
        },
        {
          "group": "com.theoplayer.theoplayer-sdk-android",
          "module": "basic-minapi21",
          "version": {
            "requires": "4.12.2"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-cast-framework",
          "version": {
            "requires": "21.3.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.picasso",
          "module": "picasso",
          "version": {
            "requires": "2.71828"
          }
        }
      ],
      "files": [
        {
          "name": "spalla-android-sdk-1.2.0.aar",
          "url": "spalla-android-sdk-1.2.0.aar",
          "size": 159555,
          "sha512": "98c546a73e4611d46f8b0ccb6a6c8c4cf193afe5ca3d901e617d70bab964aab3842bf7aad7b804389b6b8cfcf64ad3c6e3de909781bddc06dd5076763bd5882c",
          "sha256": "556b883ade442e4f0b64f39d613f9489102fbad75a2b860ce907e6309c73b757",
          "sha1": "5d31c846c50fe41f36bd9ea8e002cfa42aeda047",
          "md5": "c595861678ee4e378b4792484a761178"
        }
      ]
    }
  ]
}
