{
  "formatVersion": "1.1",
  "component": {
    "group": "stream.spalla",
    "module": "spalla-android-sdk",
    "version": "1.9.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.11.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "spalla-android-sdk-1.9.1.aar",
          "url": "spalla-android-sdk-1.9.1.aar",
          "size": 541888,
          "sha512": "7e2c07f36cf11f99b1d0a21db52ec6eaf73de527a3bd765bef864a91b335d4050164f525a5723e87b8b937fd79182a1cf739a84299b9137579adaab43bc5b80a",
          "sha256": "7ac09e298521df0537ecd3f5503ad1e75e79ee95010eb55f3d3a404297a4ffff",
          "sha1": "f7d0e9e89446ac7eb9dda08e83d53ce61bee82aa",
          "md5": "a7b1418e742dd641fb11df5380f7579d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.2.1"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2025.07.00"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-extended"
        },
        {
          "group": "com.theoplayer.theoplayer-sdk-android",
          "module": "core",
          "version": {
            "requires": "9.8.2"
          }
        },
        {
          "group": "com.theoplayer.theoplayer-sdk-android",
          "module": "integration-cast",
          "version": {
            "requires": "9.5.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-cast-framework",
          "version": {
            "requires": "22.1.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.picasso",
          "module": "picasso",
          "version": {
            "requires": "2.71828"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.11.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "spalla-android-sdk-1.9.1.aar",
          "url": "spalla-android-sdk-1.9.1.aar",
          "size": 541888,
          "sha512": "7e2c07f36cf11f99b1d0a21db52ec6eaf73de527a3bd765bef864a91b335d4050164f525a5723e87b8b937fd79182a1cf739a84299b9137579adaab43bc5b80a",
          "sha256": "7ac09e298521df0537ecd3f5503ad1e75e79ee95010eb55f3d3a404297a4ffff",
          "sha1": "f7d0e9e89446ac7eb9dda08e83d53ce61bee82aa",
          "md5": "a7b1418e742dd641fb11df5380f7579d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spalla-android-sdk-1.9.1-sources.jar",
          "url": "spalla-android-sdk-1.9.1-sources.jar",
          "size": 97148,
          "sha512": "b64a0395824ef7805c47d1980e65b60520bc38175a524ecf88d7e58430c88eb4ab8f0d8552c043d28c982a3d22a916f414407ebeaace1a99b0fd1fc86c8b29f7",
          "sha256": "7dffe123370efb8fb4c62c61837bb73b28d793a2ac3ed236cc0565cc14638257",
          "sha1": "8e14b4f12004411a00e59d81e8ff30acbcd35544",
          "md5": "cdd006b4104a98a53bb4f70ec58ce239"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spalla-android-sdk-1.9.1-javadoc.jar",
          "url": "spalla-android-sdk-1.9.1-javadoc.jar",
          "size": 503527,
          "sha512": "f6a6dd37df52b7cf5f15ded8cf25e3b30f643f1270cbc155504afeed64d2c29d0ed4dbfedba0bc47d1ce2d96bc3453be3d92f2a4b0e2efd793c66517b4cba118",
          "sha256": "9fa195e2f46fc9143fd982514c7cfe6d55f737b87c9bcebfec3936d1a4d83d60",
          "sha1": "887240a4fc07a7c4920bc4037d1f7a4cc40d43b8",
          "md5": "ea5f7a7ca76addd22bc1cf132b72634f"
        }
      ]
    }
  ]
}
