{
  "formatVersion": "1.1",
  "component": {
    "group": "stream.spalla",
    "module": "spalla-android-sdk",
    "version": "1.11.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.9.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "spalla-android-sdk-1.11.1.aar",
          "url": "spalla-android-sdk-1.11.1.aar",
          "size": 557575,
          "sha512": "2004216a09d947331bf37175d12ab426ad58b9705274810b3dd40ac1f37a2a982ec85ccde05fcf777fff596113207e22e77cec42e51ea60d81f2e0f849f7f6de",
          "sha256": "99e208fc6fcaefc24347f7902ebfa6c77bd914b0b6110af46e85df13b2efcb14",
          "sha1": "fd9889ea1656d043fd5147afbf6d9aa28e842bd4",
          "md5": "50aee3d73699299abb876f5b0d05f46a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.4"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2024.10.01"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-extended"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "com.theoplayer.theoplayer-sdk-android",
          "module": "core",
          "version": {
            "requires": "10.9.0"
          }
        },
        {
          "group": "com.theoplayer.theoplayer-sdk-android",
          "module": "integration-cast",
          "version": {
            "requires": "10.9.0"
          }
        },
        {
          "group": "com.theoplayer.theoplayer-sdk-android",
          "module": "integration-ads-ima",
          "version": {
            "requires": "10.9.0"
          }
        },
        {
          "group": "com.theoplayer.theoplayer-sdk-android",
          "module": "integration-ads-dai",
          "version": {
            "requires": "10.9.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-cast-framework",
          "version": {
            "requires": "21.3.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.picasso",
          "module": "picasso",
          "version": {
            "requires": "2.71828"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.9.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "spalla-android-sdk-1.11.1.aar",
          "url": "spalla-android-sdk-1.11.1.aar",
          "size": 557575,
          "sha512": "2004216a09d947331bf37175d12ab426ad58b9705274810b3dd40ac1f37a2a982ec85ccde05fcf777fff596113207e22e77cec42e51ea60d81f2e0f849f7f6de",
          "sha256": "99e208fc6fcaefc24347f7902ebfa6c77bd914b0b6110af46e85df13b2efcb14",
          "sha1": "fd9889ea1656d043fd5147afbf6d9aa28e842bd4",
          "md5": "50aee3d73699299abb876f5b0d05f46a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spalla-android-sdk-1.11.1-sources.jar",
          "url": "spalla-android-sdk-1.11.1-sources.jar",
          "size": 100319,
          "sha512": "3b748f13372a47de376e3322151ba4927d9bccfb7999c0416d2d4881b5e00878f4acb437485c6ac0f6facad6dbbea75c6fb92d7d955c752751c27e274b91c9b7",
          "sha256": "036d059515fc8647859d221d5e4fc4ab7449669d012d67aa8cea327df70ab228",
          "sha1": "fd769799d3741f2010f320d4444e3ea181d1eaa0",
          "md5": "a5b32831c7c69bea2c6b6809e9161fcd"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spalla-android-sdk-1.11.1-javadoc.jar",
          "url": "spalla-android-sdk-1.11.1-javadoc.jar",
          "size": 527187,
          "sha512": "65fb0afa14f23d56b290db8f7aa6cb3d926545cfc034c40751c35eb190bad14685d4276576c99f948fe88e504bef53c0230d3e7337240f17cf69b7438d7bb308",
          "sha256": "127376d22c466f07555e337672d0d906bd794917f4b708417650349ca0638c7c",
          "sha1": "e2dea0bab66e1f9583c658bc1930d877f5fb585a",
          "md5": "5e42177fd087649eecb0bd8e96394dbb"
        }
      ]
    }
  ]
}
