{
  "formatVersion": "1.1",
  "component": {
    "group": "stream.spalla",
    "module": "spalla-android-sdk",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.21"
          }
        }
      ],
      "files": [
        {
          "name": "spalla-android-sdk-1.1.0.aar",
          "url": "spalla-android-sdk-1.1.0.aar",
          "size": 159894,
          "sha512": "df52c4858c99a90b96a1d0ad233b8312f94148273ff4c039ac49a8ac4260e40ffa64fa40698cb73e06fd90ef5157cc2707014dcd3c21fd8a27d3fef00e8fbd83",
          "sha256": "612dee6c11f54d64963a87648f7e1e9fc181ee435aada2ba141d2ffefa1dce66",
          "sha1": "8a6c71a76af36302cd903ccc37f484eae4070e5c",
          "md5": "5758d192badeb768f8cc8e74062049db"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.21"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.4"
          }
        },
        {
          "group": "com.theoplayer.theoplayer-sdk-android",
          "module": "basic-minapi21",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-cast-framework",
          "version": {
            "requires": "21.3.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.picasso",
          "module": "picasso",
          "version": {
            "requires": "2.71828"
          }
        }
      ],
      "files": [
        {
          "name": "spalla-android-sdk-1.1.0.aar",
          "url": "spalla-android-sdk-1.1.0.aar",
          "size": 159894,
          "sha512": "df52c4858c99a90b96a1d0ad233b8312f94148273ff4c039ac49a8ac4260e40ffa64fa40698cb73e06fd90ef5157cc2707014dcd3c21fd8a27d3fef00e8fbd83",
          "sha256": "612dee6c11f54d64963a87648f7e1e9fc181ee435aada2ba141d2ffefa1dce66",
          "sha1": "8a6c71a76af36302cd903ccc37f484eae4070e5c",
          "md5": "5758d192badeb768f8cc8e74062049db"
        }
      ]
    }
  ]
}
