{
  "formatVersion": "1.1",
  "component": {
    "group": "stream.spalla",
    "module": "spalla-android-sdk",
    "version": "1.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "spalla-android-sdk-1.5.0.aar",
          "url": "spalla-android-sdk-1.5.0.aar",
          "size": 720402,
          "sha512": "5ac9f271a1c314135c8d16aee951781a767f9b358e91140e6b3174d9023f6e7233b447979432a8ddd58b91bd2e88dd075e46e21f0db9314e164386841d50c2bf",
          "sha256": "9368b8f2d9b94fd8f46397ad952b0eef3d2693679c58db2dc8eba83da17e1646",
          "sha1": "87a471e4e3905b00def8162f6580a374a8724e17",
          "md5": "ca1d2999c48a03f55386fe8dc8418f99"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.4"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2024.10.01"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-extended"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "com.theoplayer.theoplayer-sdk-android",
          "module": "core",
          "version": {
            "requires": "8.10.0"
          }
        },
        {
          "group": "com.theoplayer.theoplayer-sdk-android",
          "module": "integration-cast",
          "version": {
            "requires": "8.10.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-cast-framework",
          "version": {
            "requires": "21.3.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.picasso",
          "module": "picasso",
          "version": {
            "requires": "2.71828"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "spalla-android-sdk-1.5.0.aar",
          "url": "spalla-android-sdk-1.5.0.aar",
          "size": 720402,
          "sha512": "5ac9f271a1c314135c8d16aee951781a767f9b358e91140e6b3174d9023f6e7233b447979432a8ddd58b91bd2e88dd075e46e21f0db9314e164386841d50c2bf",
          "sha256": "9368b8f2d9b94fd8f46397ad952b0eef3d2693679c58db2dc8eba83da17e1646",
          "sha1": "87a471e4e3905b00def8162f6580a374a8724e17",
          "md5": "ca1d2999c48a03f55386fe8dc8418f99"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spalla-android-sdk-1.5.0-sources.jar",
          "url": "spalla-android-sdk-1.5.0-sources.jar",
          "size": 93105,
          "sha512": "78599e71c9960980ee1e597a688f15d63eb16bda02918195b2dd4275adc7b4a18ffc497d7db7d78614a5e5525360f84c4517765e98af82049d1096c231a5ddbe",
          "sha256": "70d7aedd7f72a6c53a0d1cf53ddc09a13d7f84780e5d7dd462ae2e059a93fe01",
          "sha1": "2fb9b14a7a7ca276337b5f849f4834bb55ccc2cd",
          "md5": "192754a06cf7635185bbe92afec7f8ef"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spalla-android-sdk-1.5.0-javadoc.jar",
          "url": "spalla-android-sdk-1.5.0-javadoc.jar",
          "size": 484392,
          "sha512": "4e33b989e172f9c145cb5a744f581b51bfaced0c863bedd3af6cfe2588d1703288bc9705da555a79e56e355c971c0527146bc2c0b9284c75c521d2182a5cc462",
          "sha256": "4480aa39405ab354d497812c5ed498be38cc3040a4c9b1a5533934aec0fada7d",
          "sha1": "6ec1526ca1c5807faf8a41d032457b6255e97c98",
          "md5": "e182ed4138c64ffec3d06faf4b317d77"
        }
      ]
    }
  ]
}
