{
  "formatVersion": "1.1",
  "component": {
    "group": "stream.spalla",
    "module": "spalla-android-sdk",
    "version": "1.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "spalla-android-sdk-1.7.0.aar",
          "url": "spalla-android-sdk-1.7.0.aar",
          "size": 733588,
          "sha512": "c57d4755e4318dea09caccf63fd5bf3f8de183b90753582fae82693a41e7a650b8ca6fa76cdb58077057941dfd947164bd39ccd13d033b271c803758532864c4",
          "sha256": "0e28a23bce13877ed6da1bf37ba3210913580a4dbe94eefea249f243f2e2b6ee",
          "sha1": "366ff64b375614b25d6f2e38864fd94b95ec6e92",
          "md5": "d30cedf8309a5794a660fc611c299a22"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.4"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2024.10.01"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-extended"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "com.theoplayer.theoplayer-sdk-android",
          "module": "core",
          "version": {
            "requires": "8.10.0"
          }
        },
        {
          "group": "com.theoplayer.theoplayer-sdk-android",
          "module": "integration-cast",
          "version": {
            "requires": "8.10.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-cast-framework",
          "version": {
            "requires": "21.3.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.picasso",
          "module": "picasso",
          "version": {
            "requires": "2.71828"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "spalla-android-sdk-1.7.0.aar",
          "url": "spalla-android-sdk-1.7.0.aar",
          "size": 733588,
          "sha512": "c57d4755e4318dea09caccf63fd5bf3f8de183b90753582fae82693a41e7a650b8ca6fa76cdb58077057941dfd947164bd39ccd13d033b271c803758532864c4",
          "sha256": "0e28a23bce13877ed6da1bf37ba3210913580a4dbe94eefea249f243f2e2b6ee",
          "sha1": "366ff64b375614b25d6f2e38864fd94b95ec6e92",
          "md5": "d30cedf8309a5794a660fc611c299a22"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spalla-android-sdk-1.7.0-sources.jar",
          "url": "spalla-android-sdk-1.7.0-sources.jar",
          "size": 95541,
          "sha512": "1435bb145eca912bf86ad0a5e25b5bd28006b5f833e9533f7b44dfe6aafb8984ad0c8502ec1d91d9bba140d483409b78648df20f6d1c7e9a67baef420cb602dc",
          "sha256": "f80fefae3192f24b4123d72dc5d78032da722a2af53fb2ee4bb8ed22741bd8ee",
          "sha1": "347c678333aec9d26c45bec14d558158cc24a9cd",
          "md5": "ee1491d8f7d508a5c5a340897bfd8059"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spalla-android-sdk-1.7.0-javadoc.jar",
          "url": "spalla-android-sdk-1.7.0-javadoc.jar",
          "size": 496988,
          "sha512": "0e4fe5c05a887a0c246e81831e2ece8009fc7d2965030353b5d8893d611fb90f4537cf075e161110985abba86378730154b09f9542388ee5a4d993d86d8ce3a5",
          "sha256": "8897d62b9c45c6cb921644b3a9450efbab648cc5439fbe4397cc290853e20b9b",
          "sha1": "e2ac761f1bbdff6f7a7ce5968031123bd5ad9c9f",
          "md5": "7fd0f6056cb541414305997b7573e357"
        }
      ]
    }
  ]
}
