{
  "formatVersion": "1.1",
  "component": {
    "group": "stream.spalla",
    "module": "spalla-android-sdk",
    "version": "1.8.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "spalla-android-sdk-1.8.0.aar",
          "url": "spalla-android-sdk-1.8.0.aar",
          "size": 738218,
          "sha512": "2562e891e9d59aa61f315a7bdf47089ad9de748dda0486f501b74d2d1454a09ad44636c6d2a4b755781e0349942930b4bbcbe5513f14e5056f9e452c801222f4",
          "sha256": "90c75842531372a5c8d32cdd194f9ca822a863fe44dad7ef631b550044730876",
          "sha1": "84fd97534368fb3cce2006ff46f06c4a7a10f41c",
          "md5": "152b0733461052b325fdaa7dcc110491"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.4"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2024.10.01"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-extended"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "com.theoplayer.theoplayer-sdk-android",
          "module": "core",
          "version": {
            "requires": "8.10.0"
          }
        },
        {
          "group": "com.theoplayer.theoplayer-sdk-android",
          "module": "integration-cast",
          "version": {
            "requires": "8.10.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-cast-framework",
          "version": {
            "requires": "21.3.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.picasso",
          "module": "picasso",
          "version": {
            "requires": "2.71828"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "spalla-android-sdk-1.8.0.aar",
          "url": "spalla-android-sdk-1.8.0.aar",
          "size": 738218,
          "sha512": "2562e891e9d59aa61f315a7bdf47089ad9de748dda0486f501b74d2d1454a09ad44636c6d2a4b755781e0349942930b4bbcbe5513f14e5056f9e452c801222f4",
          "sha256": "90c75842531372a5c8d32cdd194f9ca822a863fe44dad7ef631b550044730876",
          "sha1": "84fd97534368fb3cce2006ff46f06c4a7a10f41c",
          "md5": "152b0733461052b325fdaa7dcc110491"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spalla-android-sdk-1.8.0-sources.jar",
          "url": "spalla-android-sdk-1.8.0-sources.jar",
          "size": 96109,
          "sha512": "bf09c962e23a4d28e7d737212964dd70dfba9714ae7f0bf5d68a6a8fb3b6af886de21dae569dbdb46379f7c20694a2aa9cefb80180db2c9dfd7788b84b9bf5b4",
          "sha256": "7e5e24dd4ef4781d47c518790cddbfd53be22aa521681fdbd01c3a93e748c9e9",
          "sha1": "8b8564a0f0a8b083ea441459a0089392b3a7159a",
          "md5": "9402675e264953ad9b5f801ecbd500bb"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spalla-android-sdk-1.8.0-javadoc.jar",
          "url": "spalla-android-sdk-1.8.0-javadoc.jar",
          "size": 506558,
          "sha512": "b9e3da53d1aceea57619ed19dcb2e06b1ecf621ddb67701091ba6bd7959d7c5b7aa4e416ac9d0f4a0a5cb6185536268a8475aed63e7853bba6f5203a249f898a",
          "sha256": "f0177739167402883d3aeb87bb55f30afe135ea640dc548282cf85cfa404856e",
          "sha1": "8a393b1f9e2cf11db521c821425e40b68c4ca06e",
          "md5": "302d6ef9e26a89d275a6d5a385462b27"
        }
      ]
    }
  ]
}
