{
  "formatVersion": "1.1",
  "component": {
    "group": "stream.spalla",
    "module": "spalla-android-sdk",
    "version": "1.8.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "spalla-android-sdk-1.8.1.aar",
          "url": "spalla-android-sdk-1.8.1.aar",
          "size": 744464,
          "sha512": "df431203075367410e6d4407bd726a86766fa2ab988025350fac981c35da03cd56e421a6b9d1d93832dd9b083441ccbb82770e4abb0bec71b1dbcb5da3a9c69e",
          "sha256": "29daf91ae6f1d5b08a229431753b4bfc9e119777ea925312baf733617be726ab",
          "sha1": "d31b217c3e19334775e6fbf08b27e62761205343",
          "md5": "2d27f0756068730eaa3f07a4ce98b4d6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.4"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2024.10.01"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-extended"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "com.theoplayer.theoplayer-sdk-android",
          "module": "core",
          "version": {
            "requires": "8.10.0"
          }
        },
        {
          "group": "com.theoplayer.theoplayer-sdk-android",
          "module": "integration-cast",
          "version": {
            "requires": "8.10.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-cast-framework",
          "version": {
            "requires": "21.3.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.picasso",
          "module": "picasso",
          "version": {
            "requires": "2.71828"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "spalla-android-sdk-1.8.1.aar",
          "url": "spalla-android-sdk-1.8.1.aar",
          "size": 744464,
          "sha512": "df431203075367410e6d4407bd726a86766fa2ab988025350fac981c35da03cd56e421a6b9d1d93832dd9b083441ccbb82770e4abb0bec71b1dbcb5da3a9c69e",
          "sha256": "29daf91ae6f1d5b08a229431753b4bfc9e119777ea925312baf733617be726ab",
          "sha1": "d31b217c3e19334775e6fbf08b27e62761205343",
          "md5": "2d27f0756068730eaa3f07a4ce98b4d6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spalla-android-sdk-1.8.1-sources.jar",
          "url": "spalla-android-sdk-1.8.1-sources.jar",
          "size": 97370,
          "sha512": "6cfdedc57e2d5b6a25f1d7cedf6b8e97782914f90827e12a0f2e341b7147baf90e78a6c06889c509d35b68f7473f00439e29961508b11c3a0313ef6e072c5906",
          "sha256": "3cf786385acdbdc6ece826a205246e47e81470f4c0c7678e69be1fb9f6b3aeae",
          "sha1": "a6e305c4885a3b9cc1553e7440c401d90f7512e3",
          "md5": "82c9696e78cd88bccbbf5d7f059589db"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spalla-android-sdk-1.8.1-javadoc.jar",
          "url": "spalla-android-sdk-1.8.1-javadoc.jar",
          "size": 506555,
          "sha512": "aaccbbab38e0b9bd71859c104bf09af0cb03d0ccbd655ba36911b10f6fa298015c8f17d1f20091ccb01625f35c90fbbc4343601493f90c800742cf266df5b266",
          "sha256": "03f79e69223170cda9b05c4e6a574a8b9d7d6bc76a4f22f3fa4d28866a17c877",
          "sha1": "c56c7a4ae9afc5be101e3686f0cfdae28bcb152d",
          "md5": "f00a3eb47468581d15b0c67e7eed624b"
        }
      ]
    }
  ]
}
